---
apiVersion: v1
kind: Secret
metadata:
  name: marvel-proxy-secret
  namespace: marvel
data:
  marvelApiPublicKey: 3d1f66d37dfce525e7bc478de3b021e8
  marvelApiPrivateKey: f0ef5215d848fad0762c6ba8cce055a72e7ad6bf
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: marvel-proxy-cert
  namespace: marvel
spec:
  secretName: marvel-proxy-cert
  commonName: proxy.marvel.techmeup.io
  dnsNames:
  - proxy.marvel.techmeup.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: marvel-proxy-ingress
  namespace: marvel
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/tls-acme: "'true'"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: proxy.marvel.techmeup.io
    http:
      paths:
      - backend:
          serviceName: marvel-proxy-service
          servicePort: 80
  tls:
  - hosts:
    - proxy.marvel.techmeup.io
    secretName: marvel-proxy-cert
---
apiVersion: v1
kind: Service
metadata:
  name: marvel-proxy-service
  namespace: marvel
spec:
  selector:
    app: marvel-proxy
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marvel-proxy
  namespace: marvel
  labels:
    app: marvel-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marvel-proxy
  template:
    metadata:
      labels:
        app: marvel-proxy
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: marvel-proxy
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
        env:
        - name: MARVEL_API_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: marvel-proxy-secret
              key: marvelApiPublicKey
        - name: MARVEL_API_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: marvel-proxy-secret
              key: marvelApiPrivateKey
