services:
- docker:dind

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - .pub_cache/

stages:
  - tests
  - build
  - deploy

tests:
  stage: tests
  image: google/dart:latest
  before_script:
    - export PUB_CACHE=$PWD/.pub_cache
    - pub version
    - pub get
    - pub upgrade
    - pub global activate aqueduct
    - pub get --offline
    - export PATH="$PATH":"$PWD/.pub_cache/bin"
    - aqueduct document client --host=https://proxy.marvel.techmeup.io
  script:
    - pub run test

build:
  stage: build
  before_script:
    - apk update && apk upgrade && apk add --no-cache curl
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.techmeup.io
  script:
    - docker build --pull -t registry.techmeup.io/travelcar/marvel_proxy:latest -f container/prod/Dockerfile .
    - docker push registry.techmeup.io/travelcar/marvel_proxy:latest
  only:
    - master

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  environment:
    name: Production
  before_script:
    - apk update && apk upgrade && apk add --no-cache curl
  script:
    - upgrade --rancher-url $RANCHER_URL --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --environment $RANCHER_ENV --stack travelcar --service api --new-image registry.techmeup.io/travelcar/marvel_proxy:latest --create --wait-for-upgrade-to-finish --no-finish-upgrade
  after_script:
    - curl -X POST -H "Content-type:\ application/json" --data "{\"text\":\"Deploy TravelCar api $CI_COMMIT_TITLE $CI_PROJECT_URL/commit/$CI_COMMIT_SHA\"}" $SLACK_HOOK
  when: manual
  only:
    - master
