stages:
- name: testbuild
  steps:
  - runScriptConfig:
      image: google/dart:latest
      shellScript: |
        export PUB_CACHE=$PWD/.pub_cache
        pub version
        pub get
        pub upgrade
        pub global activate aqueduct
        pub get --offline
        cp config.test.yaml config.src.yaml
        export PATH="$PATH":"$PWD/.pub_cache/bin"
        pub run test
        aqueduct document client --host=https://proxy.marvel.techmeup.io
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./container/Dockerfile
      buildContext: .
      tag: marvel-proxy:${CICD_EXECUTION_SEQUENCE}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./container/deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: '#infra'
    notifier: c-55nms:n-n5knt
  condition:
  - Success
  - Changed
  - Failed
