name: marvel_proxy
description: HTTP proxy to the Marvel API.
version: 0.0.1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  file: ^5.1.0
  redis: ^1.2.1

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
